### ISSUE TITLE
gem_available? method missing

### ISSUE THREAD

**Issue by jakepenn** [magma-labs/solidus_dynamic_sitemaps#4]
Just tried installing this on a solidus `2.11.5` store -- hit undefined method `gem_available?`

Seems this has become deprecated?

**Comment by jtapia** [comment]
@jakemumu thanks, this was solved here https://github.com/magma-labs/solidus_dynamic_sitemaps/commit/a5cae78a406ae59bebd3511fce83c07bd03298d4
